### ISSUE TITLE
Bot doesn't answer on highlight if that nick is not the one from the config file

### ISSUE THREAD

**Issue by carstenhag** [lidel/meowkov#11]
Hey, the bot does not reply to messages when the config file's nick and the nick he uses differ.

This may happen when the bot is behind a bouncer (for me ZNC).

ZNC forced `GoBot` as nick and the config file had `Meowbot` in it. Saying "Gobot, Moter8" did not return any answer from it.

Changing the config file's nick to `GoBot` made it answer again.

**Comment by lidel** [comment]
Ha, nice use-case, I did not expect that :-) 
I added additional check: please do `make docker-rebuild` and let me know if it solved your problem.

**Comment by lidel** [comment]
Assuming closed ;-)
