### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by sk4zuzu** [lidel/meowkov#2]
:rocket:

**Comment by lidel** [comment]
:+1:

**Comment by lidel** [comment]
One-liner to rebuild and run: `make docker-rebuild`
It requires around 600MB for golang(500MB)+redis(100MB) base images, which are fetched when run for the first time, but thanks to this you don't need to have golang compiler in your base system.

Stop containers: `make docker-stop`
Start containers: `make docker-start`

Remove containers and custom image: `make docker-clean`

**Comment by sk4zuzu** [comment]
Thank you lidel, this is what I was waiting for :+1: 

https://yt.aergia.eu/#v=Tt-tG6ufH90&t=22s;25s

\:D/
