### ISSUE TITLE
how to build/run without docker

### ISSUE THREAD

**Issue by vimalk78** [lidel/meowkov#33]
i am behind a proxy so things are difficult already, and running docker is making it more difficult for me.

is it possible to build/run this application without involvement of docker?

thanks,

**Comment by lidel** [comment]
Yes,  you can do both.

To build: just run `make build` and statically-linked binary `meowkov` will be built.
It assumes you to have `$GOPATH`  set and `go` binary is present on your `$PATH`.

To run.. you just run the `./meowkov` binary without any arguments. 
It will use `RedisServer` defined in `meowkov.conf`, so make sure it points at existing server.

Adding to corpus: `cat text.txt | ./meowkov -import=true -purge=false`
Replacing corpus: `cat text.txt | ./meowkov -import=true -purge=true`
Help: `./meowkov -h`

Let me know if you run into any issues, it will help me to improve documentation.
